site:
  title: RISC-V ISA Documentation Library
  start_page: ROOT::index.adoc
content:
  sources:
  - url: https://github.com/riscv/riscv-isa-manual.git
    branches: antora-refactor
    start_path: antora

    #  - url: https://github.com/riscv/riscv-isa-manual.git
#branches: antora-refactor
#start_path: antora
asciidoc:
  attributes:
    page-component-order: '!ROOT, *,'
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
