site:
  title: RISC-V Ratified Specifications Library
    #url: https://docs.riscv.org

content:
  sources:
  - url: https://github.com/riscv/riscv-isa-manual.git
    branches: antora-refactor
    start_page: ROOT::index.adoc
    start_path: /

  - url: https://github.com/riscv-non-isa/e-trace-encap.git
    branches: antora-refactor
    #tags: [v1.0]
    start_page: ROOT::header.adoc
    start_path: /

  - url: https://github.com/riscv-non-isa/riscv-elf-psabi-doc.git
    branches: antora-refactor
    start_page: ROOT::introduction.adoc
    start_path: /

  - url: https://github.com/riscv-non-isa/riscv-cbqri.git
    branches: antora-refactor
    start_page: ROOT::index.adoc
    start_path: /

asciidoc:
  extensions:
  - asciidoctor-kroki
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
    le: '&#8804;'
    ge: '&#8805;'
    ne: '&#8800;'
    approx: '&#8776;'
    inf: '&#8734;'
    csrname: 'envcfg'
    incexample: example$
    incimage: ../images/

antora:
   extensions:
   - '@antora/pdf-extension'

runtime:
  fetch: true

ui:
  bundle:
    #url: https://github.com/boozallen/sdp-docs-skin/releases/download/1.2/ui-bundle.zip
    #url: https://github.com/apache/camel-website/releases/latest/ui-bundle.zip
    #url: https://github.com/mulesoft/docs-site-ui/releases/download/prod-627/ui-bundle.zip
    #url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    url: https://github.com/spring-io/antora-ui-spring/releases/download/v0.4.16/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui
