site:
  title: RISC-V ISA Documentation Library Antora Demo Site
  url: https://docs.riscv.org
  start_page: riscv-library::index.adoc
content:
  sources:
  - url: https://github.com/riscv/riscv-library.git
    branches: main
    start_path: /
  - url: https://github.com/riscv/riscv-isa-manual.git
    branches: antora-refactor
    start_path: /
#  - url: https://github.com/riscv-admin/policies.git
#    branches: 6-update-repo-structure-description-for-antora-layout

    #  - url: https://github.com/riscv/riscv-isa-manual.git
#branches: antora-refactor
#start_path: antora
asciidoc:
  extensions:
  - asciidoctor-kroki
  #- asciidoctor-mathematical

ui:
  bundle:
    #url: https://github.com/mulesoft/docs-site-ui/releases/download/prod-627/ui-bundle.zip
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
